
/*
 * respect.js #

This is a module-level docstring, and will be displayed at the top of the module documentation.
Documentation generated by [CoffeeDoc](http://github.com/omarkhan/coffeedoc)
 */

(function() {
  var Comparator, RespectPlugin, exports,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Comparator = require('./comparator');

  RespectPlugin = (function(superClass) {
    extend(RespectPlugin, superClass);

    function RespectPlugin() {
      return RespectPlugin.__super__.constructor.apply(this, arguments);
    }


    /*
    RespectPlugin
     */

    RespectPlugin.prototype.KEYWORD = 'respect';

    RespectPlugin.prototype.chaiAssert = function(ctx) {
      var keyword;
      keyword = this.KEYWORD;
      return ctx.assert(this.conform, "expected " + '#{this}' + " to " + keyword + " " + '#{exp}', "expected " + '#{this}' + " not to " + keyword + " " + '#{exp}' + " (false negative fail)", this.expected, this.displayActual);
    };

    RespectPlugin.prototype.shouldAssert = function(ctx) {
      ctx.params = {
        operator: "to " + this.KEYWORD,
        expected: this.expected
      };
      if (!this.conform) {
        return ctx.fail();
      }
    };


    /*
    STATICS
     */

    RespectPlugin.parseCustom = function(rawOptions) {
      var alias, defaultValue, optionName, options, ref;
      alias = rawOptions != null ? rawOptions.alias : void 0;
      options = {};
      ref = this.DEFAULT_OPTIONS;
      for (optionName in ref) {
        defaultValue = ref[optionName];
        options[optionName] = rawOptions != null ? rawOptions[optionName] : void 0;
        if (options[optionName] == null) {
          options[optionName] = defaultValue;
        }
      }
      return [alias, options];
    };

    RespectPlugin.spawnSubClass = function(options) {
      var ComparatorClass, alias, ref;
      ComparatorClass = (function(superClass1) {
        extend(ComparatorClass, superClass1);

        function ComparatorClass() {
          return ComparatorClass.__super__.constructor.apply(this, arguments);
        }

        return ComparatorClass;

      })(this);
      ref = this.parseCustom(options), alias = ref[0], options = ref[1];
      if (alias) {
        ComparatorClass.prototype.KEYWORD = alias;
      }
      ComparatorClass.DEFAULT_OPTIONS = options;
      return ComparatorClass;
    };

    RespectPlugin.chaiPlugin = function(options) {
      return (function(_this) {
        return function(chai, utils) {
          var ComparatorClass;
          ComparatorClass = _this.spawnSubClass(options);
          return utils.addMethod(chai.Assertion.prototype, ComparatorClass.prototype.KEYWORD, function(expected, options) {
            var comparator;
            comparator = new ComparatorClass(expected, this._obj, options);
            return comparator.chaiAssert(this);
          });
        };
      })(this);
    };

    RespectPlugin.shouldPlugin = function(options) {
      return (function(_this) {
        return function(should, Assertion) {
          var ComparatorClass;
          ComparatorClass = _this.spawnSubClass(options);
          return Assertion.add(ComparatorClass.prototype.KEYWORD, function(expected, options) {
            var comparator;
            comparator = new ComparatorClass(expected, this.obj, options);
            return comparator.shouldAssert(this);
          });
        };
      })(this);
    };

    return RespectPlugin;

  })(Comparator);

  exports = module.exports = RespectPlugin;

}).call(this);
